<!doctype html>
<html lang="id">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="theme-color" content="#0b382f">
  <meta name="description" content="Undangan pernikahan Arya Saloka dan Emira Feriha, 30 September 2026 di Makassar.">
  <title>Arya Saloka &amp; Emira Feriha | Undangan Pernikahan</title>
  <link rel="icon" type="image/svg+xml" href="favicon.svg">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,400;0,500;0,600;1,400;1,500&family=Manrope:wght@400;500;600;700&display=swap" rel="stylesheet">
  <style>
    :root{--green:#0b382f;--deep:#092b26;--paper:#f8f7f1;--gold:#c7ad7a;--text:#123c34;--sans:"Manrope",Arial,sans-serif;--serif:"Cormorant Garamond",Georgia,serif}
    *{box-sizing:border-box}html{scroll-behavior:smooth;scroll-padding-top:36px}body{margin:0;background:var(--paper);color:var(--text);font:16px/1.7 var(--sans)}button,input,select,textarea{font:inherit}button{cursor:pointer}a{color:inherit;text-decoration:none}img{display:block;width:100%}h1,h2,h3,p,figure{margin:0}h1,h2,h3{font-family:var(--serif);font-weight:500}h2{font-size:clamp(3.25rem,6vw,6rem);line-height:.98;letter-spacing:-.045em}em{font-weight:400}::selection{background:var(--gold);color:var(--deep)}:focus-visible{outline:2px solid var(--gold);outline-offset:4px}
    .shell{width:min(1180px,calc(100% - 88px));margin:auto}.section{padding:clamp(85px,10vw,150px) 0}.eyebrow{font-size:.74rem;font-weight:700;letter-spacing:.23em;color:var(--gold);line-height:1.4}.eyebrow.dark{color:#887651}.reveal{transition:opacity .75s ease,transform .75s ease}.motion .reveal:not(.visible){opacity:0;transform:translateY(26px)}
    .hero{min-height:100svh;background:var(--green);color:#f6f2e7;display:flex;flex-direction:column;overflow:hidden}.topbar{width:min(1390px,calc(100% - 88px));height:92px;margin:auto auto 0;display:grid;grid-template-columns:1fr auto 1fr;align-items:center;border-bottom:1px solid #ffffff33;position:relative;z-index:5}.brand{font:2rem/1 var(--serif);letter-spacing:-.06em;width:max-content}.brand span{color:var(--gold);font-style:italic}.links{display:flex;gap:clamp(18px,2.5vw,40px)}.links a{font-size:.76rem;color:#e4e7dd}.links a:hover{color:var(--gold)}.top-date{justify-self:end;color:var(--gold);font-size:.73rem;font-weight:700;letter-spacing:.15em}.menu{display:none}
    .hero-inner{width:min(1390px,calc(100% - 88px));margin:auto;display:grid;grid-template-columns:1fr 46%;align-items:center;gap:clamp(35px,6vw,105px);padding:40px 0}.hero-copy{padding-left:clamp(0px,4vw,70px)}.hero-copy .eyebrow:before{content:"";display:inline-block;width:35px;height:1px;background:var(--gold);vertical-align:middle;margin-right:15px}.hero h1{font-size:clamp(6rem,10.8vw,11.4rem);line-height:.72;letter-spacing:-.07em;margin:46px 0 0}.hero h1 em{color:var(--gold);font-size:.62em}.hero-full{margin-top:37px;font-size:.85rem;letter-spacing:.17em;text-transform:uppercase}.hero-full i{font:italic 1.35rem var(--serif);text-transform:none;letter-spacing:0;color:var(--gold);padding:0 8px}.divider{display:block;width:58px;height:1px;background:var(--gold);margin:30px 0 22px}.hero-date{font-size:1.04rem}.hero-date small{display:block;color:#a8c0b5;font-size:.88rem}.primary-button{background:#f5f0df;border:0;color:var(--deep);padding:15px 24px;min-height:54px;font-size:.81rem;font-weight:700;display:inline-flex;align-items:center;gap:26px;transition:background .2s}.primary-button:hover{background:var(--gold)}.hero .primary-button{margin-top:34px}.hero-picture{position:relative;padding:13px 13px 0 0;width:min(100%,525px);justify-self:end}.hero-picture:after{content:"";position:absolute;inset:0 0 39px 13px;border:1px solid var(--gold);pointer-events:none}.hero-picture img{height:clamp(500px,60vh,710px);object-fit:cover;object-position:center 50%;transform:translateY(calc(var(--shift,0px) * -.22));background:#315749}.picture-note{display:flex;justify-content:space-between;padding-top:17px;color:#d4d2bd;font-size:.63rem;letter-spacing:.18em}.hero-bottom{width:min(1390px,calc(100% - 88px));margin:auto auto 0;min-height:62px;border-top:1px solid #ffffff33;display:flex;align-items:center;justify-content:space-between;color:#b9c9bd;font-size:.72rem}.hero-bottom a{font-size:.66rem;letter-spacing:.16em;color:#f4edd8}
    .count{background:#f4f2e9;text-align:center}.count h2{margin:22px 0}.count p{color:#62746a}.timer{display:flex;max-width:700px;margin:50px auto 55px}.timer>div{flex:1;border-right:1px solid #d9dbd2}.timer>div:last-child{border:0}.timer strong{display:block;font:500 clamp(3.8rem,7vw,7rem)/1 var(--serif);letter-spacing:-.06em;font-variant-numeric:tabular-nums}.timer span{display:block;margin-top:9px;font-size:.7rem;letter-spacing:.2em;text-transform:uppercase;color:#82734f;font-weight:700}.count-footer{display:flex;justify-content:center;align-items:center;gap:20px;font-size:.68rem;letter-spacing:.13em;color:#607368}.count-footer b{color:var(--green)}.count-footer i{width:38px;height:1px;background:#c4b89b}
    .story{background:#fffefa}.story-grid{display:grid;grid-template-columns:47% 1fr;gap:clamp(60px,10vw,165px);align-items:center}.story-photo{position:relative;padding:0 43px 38px 0}.story-photo:before{content:"";position:absolute;inset:33px 0 0 34px;border:1px solid #bfaa7f}.story-photo img{position:relative;aspect-ratio:4/5;object-fit:cover;object-position:center 35%}.story-photo figcaption{position:absolute;bottom:0;right:-12px;background:#fffefa;padding:10px 0;font:italic clamp(1.2rem,2vw,1.7rem) var(--serif);color:#887552}.story-copy h2{margin:27px 0 34px}.story-text{border-left:1px solid #bead8f;padding-left:26px;color:#54685d;font-size:.95rem;line-height:1.9}.story-text p+p{margin-top:20px}.signature{display:block;margin-top:26px;font:italic 2.2rem var(--serif);color:#a08258}
    .events{background:var(--deep);color:#f8f5e9}.center{text-align:center}.center h2{margin:20px 0}.center>p{color:#b9c6bb}.event-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:24px;margin-top:54px}.event-card{background:#faf9f4;color:var(--green)}.event-content{text-align:center;padding:46px 16px 34px}.event-card h3{font-size:clamp(3.3rem,4.3vw,4.7rem);line-height:1;margin:16px 0}.event-time{font:500 2.9rem/1 var(--serif)}.event-time small{font:700 .75rem var(--sans);letter-spacing:.17em}.small-rule{display:block;width:55px;height:1px;background:#bba87d;margin:23px auto}.venue{font-weight:700;font-size:.94rem}.city{color:#64766a;font-size:.82rem}.map{width:100%;height:205px;border:0;background:#d5e1d8}.map-link{height:62px;padding:0 26px;display:flex;justify-content:space-between;align-items:center;font-size:.78rem;font-weight:700}.map-link:hover{background:#e6ece4}
    .gallery{background:#f6f4eb}.gallery-head{display:flex;justify-content:space-between;align-items:end;margin-bottom:37px}.gallery-head h2{margin-top:18px}.gallery-controls{display:none;gap:9px}.gallery-controls button{height:44px;width:44px;border:1px solid #bdc9c0;background:transparent;color:var(--green)}.gallery-controls button:hover{background:var(--green);color:white}.gallery-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:24px}.gallery-item{position:relative;overflow:hidden;aspect-ratio:4/5;background:#dce1d5}.gallery-item img{height:100%;object-fit:cover;transition:transform .7s}.gallery-item:hover img{transform:scale(1.045)}.gallery-item:after{content:"";position:absolute;inset:50% 0 0;background:linear-gradient(transparent,#041e19aa)}.gallery-item figcaption{position:absolute;z-index:1;bottom:18px;left:21px;color:#fff;font:italic 1.6rem var(--serif)}.gallery-item figcaption span{display:block;color:#dfd0a5;font:700 .65rem var(--sans);letter-spacing:.17em}.gallery-note{color:#79877d;font-size:.75rem;text-align:right;margin-top:20px}
    .reply{background:#e9efe9}.reply-grid,.wishes-grid{display:grid;grid-template-columns:1fr 1fr;align-items:center;gap:clamp(45px,10vw,145px)}.reply h2,.wishes h2{margin:20px 0 25px}.intro{color:#5c7265;max-width:450px;line-height:1.85}.ornament{font:4.7rem var(--serif);color:#809a86;margin-top:42px;letter-spacing:-.1em}.ornament span{font:1rem var(--sans);color:#b89d70;vertical-align:middle;margin:0 14px}.form-card{background:#fffefa;padding:clamp(30px,4vw,55px);box-shadow:0 25px 60px #113d2e12}.form-card h3{font-size:3.9rem;line-height:1}.form-card>p{color:#6f8276;font-size:.9rem;margin:7px 0 30px}.field{margin-bottom:22px}.field label,fieldset legend{display:block;color:#274c3f;font-size:.81rem;font-weight:700;margin-bottom:8px}.field input,.field select,.field textarea{width:100%;border:1px solid #cbd9ce;border-radius:0;background:transparent;padding:13px 15px;color:var(--green);font-size:.9rem;outline:0}.field textarea{resize:vertical}.field input:focus,.field select:focus,.field textarea:focus{border-color:#8c9f82;box-shadow:0 0 0 2px #859e8626}.field input::placeholder,.field textarea::placeholder{color:#9baaa0}fieldset{border:0;padding:0;margin:0 0 22px}.attendance{display:flex;gap:12px}.attendance label{flex:1;display:flex;align-items:center;gap:7px;border:1px solid #d3dfd4;padding:10px 12px;min-height:50px;font-size:.77rem;font-weight:600;line-height:1.3;cursor:pointer}.attendance label:has(input:checked){background:#eef4ed;border-color:#789980}.attendance input{accent-color:var(--green)}.submit{width:100%;height:53px;border:0;background:var(--green);color:#fff;padding:0 20px;display:flex;justify-content:space-between;align-items:center;font-size:.8rem;font-weight:700}.submit:hover{background:#1c5949}.submit:disabled{opacity:.65;cursor:wait}.feedback{min-height:22px;margin-top:8px;font-size:.78rem;color:#9d4949}.feedback.ok{color:#236546}
    .wishes{background:#fffefa}.wishes-grid{align-items:start}.wish-form{margin-top:34px}.wish-head{display:flex;align-items:center;gap:12px;padding-bottom:17px;border-bottom:1px solid #d6dfd5;font:1.6rem var(--serif)}.wish-list{max-height:575px;overflow-y:auto}.wish-card{display:grid;grid-template-columns:44px 1fr;gap:16px;padding:25px 0;border-bottom:1px solid #e2e8e0}.avatar{height:44px;width:44px;border-radius:50%;display:grid;place-items:center;background:#e7eee8;font:1.3rem var(--serif)}.wish-meta{display:flex;justify-content:space-between;align-items:baseline;gap:10px}.wish-meta strong{font-size:.86rem}.wish-meta time{font-size:.68rem;color:#8a9c8f;white-space:nowrap}.wish-card p{color:#617669;font-size:.85rem;line-height:1.75;margin-top:6px;white-space:pre-wrap;overflow-wrap:anywhere}.empty{padding:34px 0;color:#66796b;font-size:.9rem}.local-note{display:none;font-size:.78rem;color:#7b694d;margin-top:12px}
    .gift{background:#123e33;color:#f6f4e8;text-align:center}.gift .shell{max-width:720px}.gift h2{margin:18px 0 22px}.gift p{max-width:580px;color:#c4d2c7;margin:auto}.bank{max-width:430px;border:1px solid #e0d5b199;margin:40px auto 0;padding:30px 24px;display:flex;flex-direction:column;align-items:center}.bank-mark{font:700 1.5rem var(--sans);letter-spacing:-.1em;color:#f3ebd0;border:1px solid #c6b27d;border-radius:3px;padding:0 9px}.bank small{color:#c1d0c2;font-size:.77rem;margin-top:14px}.bank strong{font:500 clamp(2.8rem,6vw,4rem)/1.3 var(--serif)}.bank button{border:0;background:#f4f0df;color:var(--green);padding:11px 17px;margin-top:12px;font-size:.76rem;font-weight:700}.bank button:hover{background:var(--gold)}
    footer{background:var(--deep);color:#e8ede4;text-align:center;padding:88px 20px 43px}footer h2{font-size:clamp(2.7rem,5vw,4.7rem);margin:18px auto 12px}footer p{font-size:.88rem;color:#acbfb3}.footer-names{font:500 clamp(3.5rem,8vw,7rem)/1 var(--serif);letter-spacing:-.055em;margin:50px 0 10px}.footer-names em{color:var(--gold)}footer small{font-size:.69rem;letter-spacing:.2em;color:#b7bfad}footer>a{display:block;width:max-content;margin:63px auto 0;color:var(--gold);font-size:.72rem;border-bottom:1px solid;padding-bottom:5px}
    .music{position:fixed;right:20px;bottom:20px;z-index:20;display:none;flex-direction:column;align-items:flex-end;gap:7px}.music.show{display:flex}.music button{display:flex;align-items:center;gap:9px;background:#f5f1e5;color:var(--green);border:1px solid #c8b789;padding:10px 14px;box-shadow:0 10px 30px #0002;font-size:.73rem;font-weight:700}.music-status{background:#f5f1e5;color:#6b4f34;max-width:220px;padding:7px 10px;font-size:.7rem}
    @media(max-width:1050px){.shell,.topbar,.hero-inner,.hero-bottom{width:calc(100% - 50px)}.hero-copy{padding-left:0}.hero h1{font-size:clamp(5.5rem,10vw,8rem)}.hero-picture img{height:59vh;min-height:480px}.story-grid{gap:65px}.reply-grid,.wishes-grid{gap:55px}}
    @media(max-width:760px){.shell,.topbar,.hero-inner,.hero-bottom{width:calc(100% - 38px)}.section{padding:77px 0}.hero{min-height:0}.topbar{height:69px}.menu{display:grid;place-items:center;grid-column:3;justify-self:end;color:#fff;background:none;border:0;font-size:1.5rem}.top-date{display:none}.links{display:none;position:absolute;left:0;right:0;top:68px;background:#123e33;border:1px solid #ece4c440;padding:17px 20px;flex-direction:column;gap:0;box-shadow:0 12px 24px #0003}.links.open{display:flex}.links a{padding:9px 0;font-size:.88rem}.hero-inner{display:flex;flex-direction:column;gap:37px;padding:48px 0 0}.hero-copy{text-align:center;width:100%}.hero h1{font-size:clamp(5.3rem,19vw,8rem);margin-top:32px}.hero-full{font-size:.68rem;letter-spacing:.1em;margin-top:28px}.hero-full i{font-size:1.15rem}.divider{margin:18px auto 11px}.hero-date{font-size:.93rem}.hero-date small{font-size:.78rem}.hero .primary-button{margin-top:25px;min-height:50px}.hero-picture{width:min(100%,470px);padding:8px 8px 0 0;align-self:center}.hero-picture:after{inset:0 0 31px 8px}.hero-picture img{height:min(100vw,500px);min-height:0}.picture-note{font-size:.55rem;padding-top:10px}.hero-bottom{margin-top:28px;min-height:54px;font-size:.65rem}.hero-bottom a{font-size:0}.hero-bottom a:after{content:"↓";font-size:1.1rem}h2{font-size:clamp(3rem,11vw,4.6rem)}.timer{margin:35px auto 38px}.timer strong{font-size:clamp(2.7rem,11vw,4.5rem)}.timer span{font-size:.61rem;letter-spacing:.1em}.count-footer{gap:9px;font-size:.54rem;letter-spacing:.06em}.count-footer i{width:18px}.story-grid,.reply-grid,.wishes-grid{grid-template-columns:1fr;gap:55px}.story-photo{width:min(100%,480px);margin:auto}.story-photo img{aspect-ratio:1/1}.story-copy h2{margin:20px 0 27px}.story-text{font-size:.9rem}.event-grid{grid-template-columns:1fr;gap:18px;margin-top:36px}.event-content{padding:35px 12px 26px}.event-card h3{font-size:3.4rem}.map{height:185px}.gallery-head h2{max-width:280px}.gallery-controls{display:flex}.gallery-controls button{width:41px;height:41px}.gallery-grid{display:flex;overflow-x:auto;scroll-snap-type:x mandatory;gap:14px;padding-bottom:12px}.gallery-item{flex:0 0 min(76vw,310px);scroll-snap-align:start}.gallery-note{text-align:left}.ornament{display:none}.form-card{padding:30px 24px}.wish-list{max-height:520px}footer{padding:75px 20px 40px}}
    @media(max-width:400px){.hero h1{font-size:5.1rem}.attendance{flex-direction:column;gap:8px}.timer strong{font-size:2.6rem}.music{right:10px;bottom:10px}}
    @media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}.reveal,.motion .reveal:not(.visible),.gallery-item img{transition:none;transform:none;opacity:1}.hero-picture img{transform:none}}
  </style>
</head>
<body>
  <main>
    <section class="hero" id="beranda">
      <header class="topbar"><a class="brand" href="#beranda" aria-label="Arya dan Emira, kembali ke atas">A<span>&amp;</span>E</a><nav class="links" id="nav" aria-label="Navigasi utama"><a href="#kisah">Kisah</a><a href="#acara">Acara</a><a href="#galeri">Galeri</a><a href="#rsvp">RSVP</a><a href="#ucapan">Ucapan</a></nav><span class="top-date">30 · 09 · 2026</span><button class="menu" id="menu" type="button" aria-controls="nav" aria-expanded="false" aria-label="Buka menu">☰</button></header>
      <div class="hero-inner"><div class="hero-copy"><div class="eyebrow">THE WEDDING OF</div><h1>Arya <em>&amp;</em><br>Emira</h1><p class="hero-full">Arya Saloka <i>dan</i> Emira Feriha</p><span class="divider"></span><p class="hero-date">Rabu, 30 September 2026<small>Makassar, Indonesia</small></p><button class="primary-button" id="open-invitation" type="button">Buka undangan <span aria-hidden="true">↓</span></button></div><div class="hero-picture"><img src="photos/hero.webp" alt="Arya dan Emira di antara rangkaian bunga di pantai saat matahari terbenam" width="1000" height="1500" fetchpriority="high"><div class="picture-note"><span>SEBUAH AWAL, SELAMANYA</span><span>01 / 04</span></div></div></div>
      <div class="hero-bottom"><span>Dengan segala cinta, kami mengundang Anda.</span><a href="#countdown">SCROLL TO EXPLORE</a></div>
    </section>
    <section class="count section" id="countdown"><div class="shell reveal"><span class="eyebrow dark">SEBUAH HARI UNTUK DIKENANG</span><h2>Menuju hari <em>bahagia</em></h2><p>Kami tak sabar merayakan awal perjalanan ini bersama Anda.</p><div class="timer" role="timer" aria-label="Hitung mundur menuju pernikahan"><div><strong data-unit="days">--</strong><span>Hari</span></div><div><strong data-unit="hours">--</strong><span>Jam</span></div><div><strong data-unit="minutes">--</strong><span>Menit</span></div><div><strong data-unit="seconds">--</strong><span>Detik</span></div></div><div class="count-footer"><span>RABU</span><i></i><b>30 SEPTEMBER 2026</b><i></i><span>MAKASSAR</span></div></div></section>
    <section class="story section" id="kisah"><div class="shell story-grid"><figure class="story-photo reveal"><img src="photos/gallery-2.webp" alt="Arya dan Emira berjalan bersama di pantai saat senja" loading="lazy" width="780" height="1170"><figcaption>“Dari satu pertemuan, menuju selamanya.”</figcaption></figure><div class="story-copy reveal"><span class="eyebrow dark">KISAH KAMI</span><h2>Semua bermula<br>di <em>tepi senja.</em></h2><div class="story-text"><p>Arya bertemu Emira saat perempuan asal Turki itu memintanya mengambil foto di pantai menjelang senja. Obrolan singkat mereka berlanjut menjadi pertemuan keesokan harinya, lalu panggilan jarak jauh ketika Emira pulang.</p><p>Meski terpisah negara, mereka terus saling mengenal dan perlahan menyusun masa depan bersama. Arya kemudian datang ke Turki untuk menemui keluarga Emira dan meminta restu.</p><p>Setahun setelah pertemuan pertama, ia mengajak Emira kembali ke pantai yang sama. Di antara dua tiang bunga dengan matahari terbenam di belakangnya, Arya berlutut dan melamar Emira. Dengan mata berkaca-kaca, Emira menjawab ya.</p></div><span class="signature">Arya &amp; Emira</span></div></div></section>
    <section class="events section" id="acara"><div class="shell"><div class="center reveal"><span class="eyebrow">HARI YANG KAMI NANTIKAN</span><h2>Waktu &amp; <em>tempat</em></h2><p>Kehadiran Anda akan membuat hari kami semakin berarti.</p></div><div class="event-grid reveal"><article class="event-card"><div class="event-content"><span class="eyebrow dark">30 September 2026</span><h3>Akad Nikah</h3><span class="event-time">19:15 <small>WITA</small></span><span class="small-rule"></span><p class="venue">Four Points by Sheraton Makassar</p><p class="city">⌖ Makassar, Sulawesi Selatan</p></div><iframe class="map" title="Peta lokasi akad nikah di Four Points by Sheraton Makassar" src="https://www.google.com/maps?q=Four%20Points%20by%20Sheraton%20Makassar&amp;output=embed" loading="lazy" allowfullscreen></iframe><a class="map-link" href="https://www.google.com/maps/search/?api=1&amp;query=Four%20Points%20by%20Sheraton%20Makassar" target="_blank" rel="noopener noreferrer">Buka petunjuk arah <span aria-hidden="true">→</span></a></article><article class="event-card"><div class="event-content"><span class="eyebrow dark">30 September 2026</span><h3>Resepsi</h3><span class="event-time">20:16 <small>WITA</small></span><span class="small-rule"></span><p class="venue">Four Points by Sheraton Makassar</p><p class="city">⌖ Makassar, Sulawesi Selatan</p></div><iframe class="map" title="Peta lokasi resepsi di Four Points by Sheraton Makassar" src="https://www.google.com/maps?q=Four%20Points%20by%20Sheraton%20Makassar&amp;output=embed" loading="lazy" allowfullscreen></iframe><a class="map-link" href="https://www.google.com/maps/search/?api=1&amp;query=Four%20Points%20by%20Sheraton%20Makassar" target="_blank" rel="noopener noreferrer">Buka petunjuk arah <span aria-hidden="true">→</span></a></article></div></div></section>
    <section class="gallery section" id="galeri"><div class="shell"><div class="gallery-head reveal"><div><span class="eyebrow dark">GALERI KAMI</span><h2>Dalam setiap <em>bingkai</em></h2></div><div class="gallery-controls"><button type="button" id="gallery-prev" aria-label="Foto sebelumnya">←</button><button type="button" id="gallery-next" aria-label="Foto berikutnya">→</button></div></div><div class="gallery-grid reveal" id="gallery-grid" aria-label="Enam bingkai foto Arya dan Emira"><figure class="gallery-item"><img src="photos/gallery-1.webp" alt="Arya dan Emira berpelukan di tepi pantai saat senja" loading="lazy"><figcaption><span>01</span>Di tepi senja</figcaption></figure><figure class="gallery-item"><img src="photos/gallery-2-detail.webp" alt="Potret dekat Arya dan Emira yang saling memandang" loading="lazy"><figcaption><span>02</span>Saling menemukan</figcaption></figure><figure class="gallery-item"><img src="photos/gallery-3.webp" alt="Arya menggandeng Emira menari di pantai" loading="lazy"><figcaption><span>03</span>Langkah bersama</figcaption></figure><figure class="gallery-item"><img src="photos/gallery-2.webp" alt="Arya dan Emira bergandengan tangan di bibir pantai" loading="lazy"><figcaption><span>04</span>Hari yang sama</figcaption></figure><figure class="gallery-item"><img src="photos/gallery-3-detail.webp" alt="Arya dan Emira menari dengan latar matahari terbenam" loading="lazy"><figcaption><span>05</span>Selalu berdua</figcaption></figure><figure class="gallery-item"><img src="photos/gallery-1-detail.webp" alt="Potret dekat pasangan di bawah cahaya senja" loading="lazy"><figcaption><span>06</span>Sebuah janji</figcaption></figure></div><p class="gallery-note">Enam bingkai dari tiga momen foto kami.</p></div></section>
    <section class="reply section" id="rsvp"><div class="shell reply-grid"><div class="reveal"><span class="eyebrow dark">KONFIRMASI KEHADIRAN</span><h2>Temani kami di<br>hari <em>istimewa.</em></h2><p class="intro">Mohon beri kabar apakah Anda dapat hadir. Kami menantikan kebersamaan dengan Anda.</p><div class="ornament" aria-hidden="true">A <span>✦</span> E</div></div><div class="form-card reveal"><h3>RSVP</h3><p>Konfirmasi kehadiran Anda</p><form id="rsvp-form"><div class="field"><label for="rsvp-name">Nama tamu</label><input id="rsvp-name" name="name" type="text" minlength="2" maxlength="80" autocomplete="name" placeholder="Nama lengkap Anda" required></div><fieldset><legend>Kehadiran</legend><div class="attendance"><label><input type="radio" name="attendance" value="yes" checked> Ya, saya hadir</label><label><input type="radio" name="attendance" value="no"> Maaf, tidak bisa hadir</label></div></fieldset><div class="field" id="guest-field"><label for="guest-count">Jumlah tamu yang hadir</label><select id="guest-count" name="guests"><option value="1">1 orang</option><option value="2">2 orang</option><option value="3">3 orang</option><option value="4">4 orang</option><option value="5">5 orang</option></select></div><button class="submit" type="submit">Kirim konfirmasi <span aria-hidden="true">→</span></button><p class="feedback" id="rsvp-feedback" role="status" aria-live="polite"></p><p class="local-note">Mode file lokal: konfirmasi hanya tersimpan di perangkat ini.</p></form></div></div></section>
    <section class="wishes section" id="ucapan"><div class="shell wishes-grid"><div class="reveal"><span class="eyebrow dark">UCAPAN &amp; DOA</span><h2>Tinggalkan <em>pesan</em><br>untuk kami</h2><p class="intro">Setiap kata baik dari Anda akan menjadi kenangan yang kami simpan.</p><form class="wish-form" id="wish-form"><div class="field"><label for="wish-name">Nama Anda</label><input id="wish-name" name="name" type="text" minlength="2" maxlength="80" placeholder="Nama lengkap Anda" required></div><div class="field"><label for="wish-message">Ucapan &amp; doa</label><textarea id="wish-message" name="message" minlength="3" maxlength="600" rows="4" placeholder="Tulis pesan untuk Arya dan Emira..." required></textarea></div><button class="submit" type="submit">Kirim ucapan <span aria-hidden="true">→</span></button><p class="feedback" id="wish-feedback" role="status" aria-live="polite"></p><p class="local-note">Mode file lokal: ucapan hanya terlihat di perangkat ini.</p></form></div><div class="reveal"><div class="wish-head"><span aria-hidden="true">♡</span> Pesan dari orang-orang tersayang</div><div class="wish-list" id="wish-list" aria-live="polite"><p class="empty">Memuat ucapan...</p></div></div></div></section>
    <section class="gift section" id="hadiah"><div class="shell reveal"><span class="eyebrow">TANDA KASIH</span><h2>Wedding <em>gift</em></h2><p>Doa dan kehadiran Anda adalah hadiah terindah. Jika ingin mengirimkan tanda kasih, Anda dapat menggunakan rekening berikut.</p><div class="bank"><span class="bank-mark">BSI</span><small>Bank Syariah Indonesia</small><strong id="account-number">11111123938</strong><button type="button" id="copy-account">Salin nomor rekening</button></div></div></section>
    <footer><span class="eyebrow">TERIMA KASIH</span><h2>Sampai jumpa di hari bahagia kami.</h2><p>Merupakan kehormatan bagi kami untuk berbagi momen ini bersama Anda.</p><div class="footer-names">Arya <em>&amp;</em> Emira</div><small>30 SEPTEMBER 2026 · MAKASSAR</small><a href="#beranda">Kembali ke atas ↑</a></footer>
  </main>
  <audio id="wedding-audio" src="audio/wedding.mp3" loop preload="none"></audio>
  <div class="music" id="music-widget"><button type="button" id="music-button" aria-label="Putar musik" aria-pressed="false"><span id="music-icon">▶</span><span id="music-label">Putar musik</span><span aria-hidden="true">♫</span></button><span class="music-status" id="music-status" role="status" hidden></span></div>
  <script>
  (function(){
    "use strict";
    var weddingTime=new Date("2026-09-30T19:15:00+08:00").getTime();
    function updateCountdown(){var diff=Math.max(0,weddingTime-Date.now());var values={days:Math.floor(diff/86400000),hours:Math.floor(diff/3600000)%24,minutes:Math.floor(diff/60000)%60,seconds:Math.floor(diff/1000)%60};Object.keys(values).forEach(function(key){document.querySelector('[data-unit="'+key+'"]').textContent=String(values[key]).padStart(2,"0")})}
    updateCountdown();setInterval(updateCountdown,1000);
    var menu=document.getElementById("menu"),nav=document.getElementById("nav");
    menu.addEventListener("click",function(){var open=nav.classList.toggle("open");menu.setAttribute("aria-expanded",String(open));menu.setAttribute("aria-label",open?"Tutup menu":"Buka menu");menu.textContent=open?"×":"☰"});
    nav.querySelectorAll("a").forEach(function(a){a.addEventListener("click",function(){nav.classList.remove("open");menu.setAttribute("aria-expanded","false");menu.textContent="☰"})});
    if("IntersectionObserver" in window){document.documentElement.classList.add("motion");var observer=new IntersectionObserver(function(entries){entries.forEach(function(entry){if(entry.isIntersecting){entry.target.classList.add("visible");observer.unobserve(entry.target)}})},{threshold:.1});document.querySelectorAll(".reveal").forEach(function(el){observer.observe(el)})}
    if(!matchMedia("(prefers-reduced-motion: reduce)").matches){var pending=false;addEventListener("scroll",function(){if(pending)return;pending=true;requestAnimationFrame(function(){document.documentElement.style.setProperty("--shift",Math.min(scrollY*.12,85)+"px");pending=false})},{passive:true})}
    var audio=document.getElementById("wedding-audio"),music=document.getElementById("music-widget"),musicButton=document.getElementById("music-button"),musicIcon=document.getElementById("music-icon"),musicLabel=document.getElementById("music-label"),musicStatus=document.getElementById("music-status");
    function musicMessage(text){musicStatus.textContent=text;musicStatus.hidden=!text}
    function musicState(playing){musicIcon.textContent=playing?"Ⅱ":"▶";musicLabel.textContent=playing?"Jeda musik":"Putar musik";musicButton.setAttribute("aria-label",musicLabel.textContent);musicButton.setAttribute("aria-pressed",String(playing))}
    function startMusic(){audio.play().then(function(){musicMessage("")}).catch(function(){musicState(false);musicMessage("Ketuk putar untuk memulai musik.")})}
    audio.addEventListener("play",function(){musicState(true)});audio.addEventListener("pause",function(){musicState(false)});audio.addEventListener("error",function(){musicState(false);musicMessage("Musik belum dapat dimuat.")});
    document.getElementById("open-invitation").addEventListener("click",function(){music.classList.add("show");startMusic();document.getElementById("countdown").scrollIntoView({behavior:"smooth"})});
    musicButton.addEventListener("click",function(){if(audio.paused)startMusic();else audio.pause()});
    var gallery=document.getElementById("gallery-grid");function moveGallery(direction){var card=gallery.querySelector(".gallery-item");gallery.scrollBy({left:direction*(card.getBoundingClientRect().width+14),behavior:"smooth"})}document.getElementById("gallery-prev").addEventListener("click",function(){moveGallery(-1)});document.getElementById("gallery-next").addEventListener("click",function(){moveGallery(1)});
    var local=location.protocol==="file:";if(local)document.querySelectorAll(".local-note").forEach(function(el){el.style.display="block"});
    function feedback(id,text,ok){var el=document.getElementById(id);el.textContent=text;el.classList.toggle("ok",!!ok)}
    function storeLocal(key,item){var data=JSON.parse(localStorage.getItem(key)||"[]");data.unshift(item);localStorage.setItem(key,JSON.stringify(data));return data}
    document.querySelectorAll('[name="attendance"]').forEach(function(radio){radio.addEventListener("change",function(){document.getElementById("guest-field").hidden=document.querySelector('[name="attendance"]:checked').value==="no"})});
    document.getElementById("rsvp-form").addEventListener("submit",async function(event){event.preventDefault();var form=event.currentTarget,button=form.querySelector("button[type=submit]"),name=form.elements.name.value.trim(),attendance=form.elements.attendance.value,guests=attendance==="yes"?Number(form.elements.guests.value):0;if(name.length<2||name.length>80)return;button.disabled=true;feedback("rsvp-feedback","Mengirim konfirmasi...",false);try{if(local)storeLocal("arya-emira-rsvps",{name:name,attendance:attendance,guests:guests});else{var response=await fetch("api/rsvp",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:name,attendance:attendance,guests:guests})});if(!response.ok)throw Error("Gagal menyimpan")}feedback("rsvp-feedback","Terima kasih, konfirmasi Anda sudah tersimpan.",true);form.reset();document.getElementById("guest-field").hidden=false}catch(error){feedback("rsvp-feedback","Maaf, konfirmasi belum terkirim. Coba lagi.",false)}finally{button.disabled=false}});
    function renderWishes(items){var list=document.getElementById("wish-list");list.replaceChildren();if(!items.length){var empty=document.createElement("p");empty.className="empty";empty.textContent="Belum ada ucapan. Jadilah yang pertama mengirim doa.";list.appendChild(empty);return}items.slice(0,30).forEach(function(wish){var card=document.createElement("article"),avatar=document.createElement("div"),body=document.createElement("div"),meta=document.createElement("div"),name=document.createElement("strong"),date=document.createElement("time"),message=document.createElement("p");card.className="wish-card";avatar.className="avatar";avatar.setAttribute("aria-hidden","true");avatar.textContent=wish.name.charAt(0).toUpperCase();meta.className="wish-meta";name.textContent=wish.name;date.dateTime=wish.createdAt;date.textContent=new Intl.DateTimeFormat("id-ID",{day:"numeric",month:"short",year:"numeric",timeZone:"Asia/Makassar"}).format(new Date(wish.createdAt));message.textContent=wish.message;meta.append(name,date);body.append(meta,message);card.append(avatar,body);list.appendChild(card)})}
    var wishes=[];async function loadWishes(){try{if(local)wishes=JSON.parse(localStorage.getItem("arya-emira-wishes")||"[]");else{var response=await fetch("api/wishes",{cache:"no-store"});if(!response.ok)throw Error("Gagal memuat");wishes=(await response.json()).wishes}renderWishes(wishes)}catch(error){document.getElementById("wish-list").innerHTML='<p class="empty">Ucapan belum dapat dimuat. Muat ulang halaman untuk mencoba lagi.</p>'}}loadWishes();
    document.getElementById("wish-form").addEventListener("submit",async function(event){event.preventDefault();var form=event.currentTarget,button=form.querySelector("button[type=submit]"),name=form.elements.name.value.trim(),message=form.elements.message.value.trim();if(name.length<2||name.length>80||message.length<3||message.length>600)return;button.disabled=true;feedback("wish-feedback","Mengirim ucapan...",false);try{var wish;if(local){wish={id:Date.now(),name:name,message:message,createdAt:new Date().toISOString()};wishes=storeLocal("arya-emira-wishes",wish)}else{var response=await fetch("api/wishes",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:name,message:message})});if(!response.ok)throw Error("Gagal menyimpan");wish=(await response.json()).wish;wishes.unshift(wish)}renderWishes(wishes);form.reset();feedback("wish-feedback","Terima kasih, ucapan Anda sudah tampil.",true)}catch(error){feedback("wish-feedback","Maaf, ucapan belum terkirim. Coba lagi.",false)}finally{button.disabled=false}});
    document.getElementById("copy-account").addEventListener("click",async function(){var button=this;try{await navigator.clipboard.writeText("11111123938");button.textContent="Tersalin";setTimeout(function(){button.textContent="Salin nomor rekening"},2500)}catch(error){var range=document.createRange();range.selectNodeContents(document.getElementById("account-number"));getSelection().removeAllRanges();getSelection().addRange(range);button.textContent="Nomor dipilih, silakan salin"}});
  })();
  </script>
</body>
</html>
